---
title: "stepwise model selection"
author: "Leslie Roberson"
date: "2025-12-31"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Summary

Stepwise model selection procedure

```{r setup, include=FALSE}

library(tidyverse)
library(here)
library(pillar)
library(mgcv)
library(MuMIn)
library(broom)

knitr::opts_chunk$set(echo = TRUE)
```

# prep data
```{r}
glimpse(model.df.wide) # 5,599 sets

model.df.v2 <- model.df.wide %>% 
  filter(fisher_ID != 14) %>% # drop fisher 14 (they drop out anyways due to many NA variables)
  filter(!month_num %in% c(6,7)) %>% # remove those closed season sets from fisher 4 (experimental trials, not normal fishing operations)
  mutate(across(c(fisher_ID, fishing_method_2), as.factor)) 
# final model df has 5,502 sets 

# format time as hour.decimal
class(model.df.v2$set_time_mod_corr)
model.df.v2$set_time_mod_corr_num <- as.numeric(model.df.v2$set_time_mod_corr) / 3600
model.df.v2$set_time_mod_corr_num <- round(model.df.v2$set_time_mod_corr_num * 6) / 6
model.df.v2$set_time_mod_corr_num <- round(model.df.v2$set_time_mod_corr_num, 1)

```

# recode month in best models

```{r recode month}
model.df.v2 <- model.df.v2 %>%
  mutate(
    cal_month = month(fishing_date_mod),          # 1 = Jan, ..., 12 = Dec
    season_month = case_when(
      cal_month >= 8  ~ cal_month - 7,     # Aug–Dec 1–5
      cal_month <= 5  ~ cal_month + 5,     # Jan–May 6–10
      TRUE            ~ NA_real_           # Jun–Jul (no fishing)
    )
  )
```

# global models 

```{r global models}

##_______________________ DOLPHINS
dols.global <- gam(dolphins_cnt ~ year + s(all_tuna_likes_kg) + s(non_tuna_retained_kg) + s(season_month, k=3) + s(latitude_set_dd_mod, longitude_set_dd_mod) + s(set_time_mod_corr_num) + s(fishing_method_2, bs = "re") + s(fisher_ID, bs = "re"), offset = log(net_area_m2), data = model.df.v2, family = tw(), na.action="na.omit", method="REML", select=TRUE)
AIC(dols.glob.2) 
summary(dols.glob.2) 

##________________________SEA TURTLES
turts.global <- gam(turtles_cnt  ~ year + s(all_tuna_likes_kg) + s(non_tuna_retained_kg) + + s(season_month, k=3) + s(latitude_set_dd_mod, longitude_set_dd_mod) + s(set_time_mod_corr_num) + s(fishing_method_2, bs = "re") + s(fisher_ID, bs = "re"),
  offset = log(net_area_m2), data = model.df.v2, family = tw(), na.action="na.omit", method="REML", select=TRUE)
AIC(turts.glob.2) 
summary(turts.glob.2) 
```

# dredge

```{r dredge}

vars.glob <- c("all_tuna_likes_kg", "non_tuna_retained_kg", "year", "season_month", "latitude_set_dd_mod", "longitude_set_dd_mod", "set_time_mod_corr_num", "fishing_method_2", "fisher_ID", "net_area_m2")
model.df.dredge.2 <- model.df.v2[complete.cases(model.df.v2[,vars.glob]), ]
# remove the 9 sets with unknown surface v bottom sets
model.df.dredge.2 <- model.df.dredge.2 %>% filter(fishing_method_2 != "unknown")

# global models na.fail
dols.dr <- gam(dolphins_cnt ~ year + s(all_tuna_likes_kg) + s(non_tuna_retained_kg) + s(season_month, k=3) + s(latitude_set_dd_mod, longitude_set_dd_mod) + s(set_time_mod_corr_num) + s(fishing_method_2, bs = "re") + s(fisher_ID, bs = "re"),
  offset = log(net_area_m2), data = model.df.dredge.2, family = tw(), na.action="na.fail", method="REML", select=TRUE)

##________________________SEA TURTLES
turts.dr<- gam(turtles_cnt  ~ year + s(all_tuna_likes_kg) + s(non_tuna_retained_kg) + + s(season_month, k=3) + s(latitude_set_dd_mod, longitude_set_dd_mod) + s(set_time_mod_corr_num) + s(fishing_method_2, bs = "re") + s(fisher_ID, bs = "re"),
  offset = log(net_area_m2), data = model.df.dredge.2, family = tw(), na.action="na.fail", method="REML", select=TRUE)

# dredge
options(na.action=na.fail)
dols.dredge <- dredge(dols.dr, evaluate=TRUE, trace=2) 
dols.dredge # the top 4 models tie so choose the simplest one

options(na.action=na.fail)
turts.dredge <- dredge(turts.dr, evaluate=TRUE, trace=2) 
turts.dredge2 # top 2 tie so choose the simpler one (without fishing method 2)
```

# dredge sum of weights
```{r dredge sw}

d <- janitor::clean_names(turts.dredge)
#d <- janitor::clean_names(dols.dredge)

weight_col <- grep("weight", names(d), value = TRUE)
# Convert predictor columns to TRUE/FALSE (dredge uses "+" and NA)
predictor_cols <- setdiff(names(d), c("model", "aicc", "delta", weight_col))
# Calculate sw() manually
sw_table <- d %>%
  mutate(across(all_of(predictor_cols), as.character)) %>%  
  pivot_longer(cols = all_of(predictor_cols),
               names_to = "predictor",
               values_to = "present") %>%
  mutate(present = !is.na(present) & present != "0") %>%     
  group_by(predictor) %>%
  summarise(sw = sum(.data[[weight_col]][present])) %>%
  arrange(desc(sw))
sw_table
# for turtles, it's fisher year and tuna = 1
# then season month, lat lon, set time, fishing method, non tuna 

# fisher and year are the only 1.000 for dolphins
# in order of importance: fisher, year, tuna, non tuna, set time, season month, fishing method, lat lon month
```

# Run best models with random effect
Run best model with fisher as a random effect
```{r best models RE}

##__________________ DOLPHINS
# best model doesn't win by >2 AIC, choose simplest one
dols.best.re<-  gam(dolphins_cnt ~ year + s(all_tuna_likes_kg) + non_tuna_retained_kg + s(set_time_mod_corr_num) + s(fisher_ID, bs = "re"),
  offset = log(net_area_m2), data = model.df.dredge, family = tw(), na.action="na.omit", method="REML", select=TRUE)
AIC(dols.best.re) 
summary(dols.best.re)
# non tuna (slight negative correlation) not significant, and set time not significant

# now compare to best model without captain factor 
dols.best.novsl <- gam(dolphins_cnt ~ year + s(all_tuna_likes_kg) + non_tuna_retained_kg + s(set_time_mod_corr_num),
  offset = log(net_area_m2), data = model.df.dredge.2, family = tw(), na.action="na.omit", method="REML", select=TRUE)
AIC(dols.best.v2.novsl) #  much worse without captain
summary(dols.best.v2.novsl) 

#_________________ TURTLES
turts.best.re<- gam(turtles_cnt  ~ year + s(all_tuna_likes_kg) + s(season_month, k=3) + s(latitude_set_dd_mod, longitude_set_dd_mod) + s(set_time_mod_corr_num) + s(fisher_ID, bs = "re"),
  offset = log(net_area_m2), data = model.df.dredge.2, family = tw(), na.action="na.omit", method="REML", select=TRUE)
AIC(turts.best.re) 

turts.best.novsl <- gam(turtles_cnt  ~ year + s(all_tuna_likes_kg) + s(season_month, k=3) + s(latitude_set_dd_mod, longitude_set_dd_mod) + s(set_time_mod_corr_num),
  offset = log(net_area_m2), data = model.df.dredge.2, family = tw(), na.action="na.omit", method="REML", select=TRUE)
AIC(turts.best.v2.novsl) # way worse

```

# Run best models with fisher as fixed effect

```{r fixed effect models}
glimpse(model.df.dredge.2)
# relevel fisher ID so captain 2 is the reference level 
model.df.dredge.2 <- model.df.dredge.2 %>% mutate(fisher_ID_relevel= factor(fisher_ID) %>% relevel(ref="2")) 
# set up paraPen
NoCoefs <- length(unique(model.df.dredge.2$fisher_ID_relevel))-1 
pp <- list(fisher_ID_relevel = list(rank = NoCoefs, diag(NoCoefs)))
# contrast coding 
contrasts(model.df.dredge.2$fisher_ID_relevel) <- contr.sum

#_____ DOLPHINS
dols.best.fe <-  gam(dolphins_cnt ~ year + s(all_tuna_likes_kg) + non_tuna_retained_kg + s(set_time_mod_corr_num) + fisher_ID_relevel,
  offset = log(net_area_m2), data = model.df.dredge.2, family = tw(), na.action="na.omit", method="REML", select=TRUE, paraPen=pp)
AIC(dols.best.fe)

#_______ TURTLES
turts.best.fe <- gam(turtles_cnt  ~ year + s(all_tuna_likes_kg) + s(season_month, k=3) + s(latitude_set_dd_mod, longitude_set_dd_mod) + s(set_time_mod_corr_num) + fisher_ID_relevel,
  offset = log(net_area_m2), data = model.df.dredge.2, family = tw(), na.action="na.omit", method="REML", select=TRUE, paraPen=pp) 
AIC(turts.best.fe) 

```

# save best model outputs
model summaries for results table
GAM plots
```{r save outputs}

library(openxlsx) 
library(mgcViz)
library(pixiedust)
library(gratia) 

#mod <- dols.best.re
mod <- turts.best.re

summary.mod <- summary(mod)
param <- rownames(summary.mod$p.table)
coeffs.out <- cbind(param, as.data.frame(summary.mod$p.table, rownames=NULL))
mod.out <- openxlsx::createWorkbook()
mod.glance <-  broom::glance(mod)
mod.sum <- pixiedust::dust(mod, glance_foot=TRUE) %>%
  sprinkle(col=2:4, round=4) %>%
  sprinkle(cols=5, fn=quote(pvalString(value))) %>%
  sprinkle(rows = 1, border = "top") %>%
  sprinkle(cols = c(2, 5), round = 2, na_string = "",
           part = "foot") %>%
  sprinkle(rows = 1, border = "top", part = "foot") %>%
  sprinkle_print_method("console")
mod.out <- createWorkbook()
addWorksheet(mod.out, "gam_glance")
addWorksheet(mod.out, "gam_summ")
addWorksheet(mod.out, "coeffs_full")
writeData(mod.out, sheet = "gam_glance", x=mod.glance)
writeData(mod.out, sheet = "gam_summ", x=mod.sum)
writeData(mod.out, sheet = "coeffs_full", x=coeffs.out)


##_________________ GAM PLOTS
summary(dols.best.re.v2.2)
p.diags.dols <- gam.check(dols.best.re)

summary(turts.best.re)
p.diags.turts <- gam.check(turts.best.re) 

# draw smooths 
smooths.dols <- gratia::draw(dols.best.re) 
smooths.turts <- gratia::draw(turts.best.re) 

```
